keys:
  - &xfo age1fenzpa09q6dgpec6yyyvh8ufdennprmvpmm474swtk760a6f3dkssxd42h

  - &AO05 age10dj68x8c9kujkvhfatlpq3vvp84v4klwmhug9evu3m2yh7dk5ahsk79v4w
  - &grpht age1fyf2l7nfm4p39ehxfutqgy0sy9jh03mw84579s0d987kzzdt3arqw9srfv
  - &nl0x age1a7e4ppqxwyk0xh73mc7aer8myw3e93q76nkh9flfcfaaaxwgxedslrtvme

creation_rules:
  - path_regex: \.secrets/users/xfo/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *xfo
          - *AO05
          - *grpht
          - *nl0x

  - path_regex: \.secrets/common/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *xfo
          - *AO05
          - *grpht
          - *nl0x

  - path_regex: \.secrets/hosts/AO05/.*\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *xfo
          - *AO05

  - path_regex: \.secrets/hosts/grpht/.*\.(yaml|json|env|ini|sops|conf)$
    key_groups:
      - age:
          - *xfo
          - *grpht

  - path_regex: \.secrets/hosts/nl0x/.*\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *xfo
          - *nl0x
