bindings = [
  { action = "ui.cancel", key = "esc", scope = "ui" },
  { action = "ui.open_help", key = "?", scope = "ui" },
  { action = "ui.quit", key = "q", scope = "ui" },
  { action = "ui.suspend", key = "ctrl+l", scope = "ui" },
  { action = "revisions.move_up", key = "n", scope = "revisions" },
  { action = "revisions.move_down", key = "e", scope = "revisions" },
  { action = "revisions.new", key = "u", scope = "revisions" },
  { action = "revisions.describe", key = "J", scope = "revisions" },
  { action = "revisions.diff_edit", key = "ctrl+z", scope = "revisions" },
  { action = "revisions.open_abandon", key = "d", scope = "revisions" },
  { action = "revset.edit", key = "w", scope = "revisions" },
  { action = "revisions.ace_jump", key = "r", scope = "revisions" },
  { action = "revisions.open_squash", key = "_", scope = "revisions" },
  { action = "revisions.refresh", key = "ctrl+o", scope = "revisions" },
  { action = "revisions.diff", key = "#", scope = "revisions" },
  { action = "revisions.commit", key = "=", scope = "revisions" },
  { action = "ui.open_undo", key = "-", scope = "revisions" },
  { action = "revisions.split", key = "%", scope = "revisions" },
  { action = "revisions.edit", key = "enter", scope = "revisions" },
  { action = "revisions.force_edit", key = "ctrl+enter", scope = "revisions" },
  { action = "revisions.jump_to_parent", key = "^", scope = "revisions" },
  { action = "revisions.jump_to_children", key = "$", scope = "revisions" },
  { action = "revisions.jump_to_working_copy", key = "@", scope = "revisions" },
  { action = "revisions.open_duplicate", key = "h", scope = "revisions" },
  { action = "revisions.open_rebase", key = "a", scope = "revisions" },
  { action = "revisions.absorb", key = "b", scope = "revisions" },
  { action = "revisions.open_revert", key = "A", scope = "revisions" },
  { action = "revisions.open_evolog", key = "m", scope = "revisions" },
  { action = "ui.open_git", key = ",", scope = "revisions" },
  { action = "ui.open_oplog", key = "M", scope = "revisions" },
  { action = "ui.open_bookmarks", key = "|", scope = "revisions" },
  { action = "ui.preview_toggle", key = "f", scope = "revisions" },
  { action = "revisions.open_inline_describe", key = "j", scope = "revisions" },
  { action = "ui.quick_search", key = "/", scope = "revisions" },
  { action = "ui.exec_shell", key = "!", scope = "revisions" },
  { action = "ui.exec_jj", key = ":", scope = "revisions" },
  { action = "revisions.toggle_select", key = " ", scope = "revisions" },
  { action = "revisions.open_set_bookmark", key = "+", scope = "revisions" },
  { action = "revisions.quick_search_next", key = "ctrl+e", scope = "revisions.quick_search" },
  { action = "revisions.move_up", key = "n", scope = "revisions.rebase" },
  { action = "revisions.move_down", key = "e", scope = "revisions.rebase" },
  { action = "revisions.rebase.ace_jump", key = "r", scope = "revisions.rebase" },
  { action = "revisions.move_up", key = "n", scope = "revisions.squash" },
  { action = "revisions.move_down", key = "e", scope = "revisions.squash" },
  { action = "revisions.squash.interactive", key = "h", scope = "revisions.squash" },
  { action = "revisions.squash.keep_emptied", key = "s", scope = "revisions.squash" },
  { action = "revisions.squash.ace_jump", key = "r", scope = "revisions.squash" },
  { action = "revisions.move_up", key = "n", scope = "revisions.revert" },
  { action = "revisions.move_down", key = "e", scope = "revisions.revert" },
  { action = "revisions.move_up", key = "n", scope = "revisions.duplicate" },
  { action = "revisions.move_down", key = "e", scope = "revisions.duplicate" },
  { action = "revisions.duplicate.ace_jump", key = "r", scope = "revisions.duplicate" },
  { action = "revisions.details.move_up", key = "n", scope = "revisions.details" },
  { action = "revisions.details.move_down", key = "e", scope = "revisions.details" },
  { action = "revisions.details.cancel", key = "c", scope = "revisions.details" },
  { action = "revisions.details.diff", key = "#", scope = "revisions.details" },
  { action = "revisions.details.restore", key = "-", scope = "revisions.details" },
  { action = "revisions.details.split", key = "%", scope = "revisions.details" },
  { action = "revisions.details.absorb", key = "k", scope = "revisions.details" },
  { action = "revisions.details.revisions_changing_file", key = "*", scope = "revisions.details" },
  { action = "revisions.details.toggle_select", key = " ", scope = "revisions.details" },
  { action = "revisions.evolog.move_up", key = "n", scope = "revisions.evolog" },
  { action = "revisions.evolog.move_down", key = "e", scope = "revisions.evolog" },
  { action = "revisions.evolog.diff", key = "d", scope = "revisions.evolog" },
  { action = "revisions.evolog.restore", key = "r", scope = "revisions.evolog" },
  { action = "revisions.move_up", key = "n", scope = "revisions.abandon" },
  { action = "revisions.move_down", key = "e", scope = "revisions.abandon" },
  { action = "revisions.abandon.ace_jump", key = "r", scope = "revisions.abandon" },
  { action = "revisions.move_up", key = "n", scope = "revisions.set_parents" },
  { action = "revisions.move_down", key = "e", scope = "revisions.set_parents" },
  { action = "revisions.set_parents.ace_jump", key = "r", scope = "revisions.set_parents" },
  { action = "revisions.inline_describe.accept", key = "enter", scope = "revisions.inline_describe" },
  { action = "ui.preview_expand", key = "alt+c", scope = "ui.preview" },
  { action = "ui.preview_shrink", key = "alt+i", scope = "ui.preview" },
  { action = "ui.preview_half_page_up", key = "alt+n", scope = "ui.preview" },
  { action = "ui.preview_half_page_down", key = "alt+e", scope = "ui.preview" },
  { action = "help.scroll_up", key = "n", scope = "help" },
  { action = "help.scroll_down", key = "e", scope = "help" },
  { action = "bookmarks.move_up", key = "n", scope = "bookmarks" },
  { action = "bookmarks.move_down", key = "e", scope = "bookmarks" },
  { action = "bookmarks.bookmark_delete", key = "d", scope = "bookmarks" },
  { action = "bookmarks.bookmark_track", key = "h", scope = "bookmarks" },
  { action = "bookmarks.bookmark_untrack", key = "s", scope = "bookmarks" },
  { action = "bookmarks.bookmark_move", key = "r", scope = "bookmarks" },
  { action = "bookmarks.bookmark_forget", key = "-", scope = "bookmarks" },
  { action = "git.move_up", key = "n", scope = "git" },
  { action = "git.move_down", key = "e", scope = "git" },
  { action = "git.fetch", key = "y", scope = "git" },
  { action = "git.push", key = "u", scope = "git" },
  { action = "oplog.move_up", key = "n", scope = "oplog" },
  { action = "oplog.move_down", key = "e", scope = "oplog" },
  { action = "oplog.restore", key = "-", scope = "oplog" },
  { action = "ui.file_search_toggle", key = "t", scope = "revisions" },
  { action = "file_search.toggle", key = "t", scope = "file_search" },
  { action = "file_search.move_up", key = "ctrl+n", scope = "file_search" },
  { action = "file_search.move_down", key = "ctrl+e", scope = "file_search" },
  { action = "file_search.apply", key = "enter", scope = "file_search" },
  { action = "file_search.edit", key = "ctrl+enter", scope = "file_search" },
]
